id: I3D309202
default_language: es
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:05.159171
last_modified: 2023-01-04 11:29:05.159182
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  0F77:
    title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of Do
      Khyentsé Yeshé Dorjé
    base_file: 0F77.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
